# ui backend docker file
FROM python:3.9-slim

WORKDIR /app

COPY ui.py /app/
COPY requirements.txt /app/

RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 8001

CMD ["uvicorn", "ui:app", "--host", "0.0.0.0", "--port", "8001"]
